### ISSUE TITLE
Write a better README.md

### ISSUE THREAD

**Issue by JS-goose** [JS-goose/js-goose.github.io#1]
The README.md on this project is lacking to say the least.  Let's spruce it up a bit.  I'm ok with ***almost*** anything as long as it:
* Explains what the project is (portfolio and project #1 in Udacity's FEND Nanodegree)
* Looks good (subjective)
* No profanity (given)
* Uses the current image on the README

**Comment by akarshsingh9** [comment]
would like to contribute on this

**Comment by JS-goose** [comment]
> 
> 
> would like to contribute on this

Alright, go for it @akarshsingh9 😃

**Comment by akarshsingh9** [comment]
Please review PR #5

**Comment by JS-goose** [comment]
Thank you for your great contributions!
