### ISSUE TITLE
Fix Footer Spilling Over

### ISSUE THREAD

**Issue by JS-goose** [JS-goose/js-goose.github.io#2]
The footer spills over on mobile as referenced by the photo below.  This is a great issue for anyone who wants to practice their debugging/Bootstrap skills.

![spilling-out-mobile](https://user-images.githubusercontent.com/30503684/47605360-fad9d080-d9ca-11e8-84c7-4758f63345cd.png)

**Comment by MrSnickers** [comment]
I would like to take this one, please.

**Comment by sadewole** [comment]
Hi JS-goose,
I've just fixed this for you

**Comment by izanf** [comment]
#8

**Comment by JS-goose** [comment]
This has been fixed, thank you to everyone for your contributions!
